<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\District;
use App\Models\State;
use Illuminate\Database\Seeder;

class CountryStateDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $country = Country::updateOrCreate(
            ['code' => 'IN'],
            ['name' => 'India']
        );

        foreach ($this->states() as $name => $state) {
            $stateModel = State::updateOrCreate(
                ['country_id' => $country->id, 'name' => $name],
                ['code' => $state['code']]
            );

            foreach ($state['districts'] as $district) {
                District::updateOrCreate([
                    'state_id' => $stateModel->id,
                    'name' => $district,
                ]);
            }
        }
    }

    /**
     * The Indian states, union territories, and their districts.
     *
     * @return array<string, array{code: string, districts: array<int, string>}>
     */
    private function states(): array
    {
        return [
            'Andhra Pradesh' => [
                'code' => 'AP',
                'districts' => [
                    'Alluri Sitharama Raju',
                    'Anakapalli',
                    'Ananthapuramu',
                    'Annamayya',
                    'Bapatla',
                    'Chittoor',
                    'Dr. B.R. Ambedkar Konaseema',
                    'East Godavari',
                    'Eluru',
                    'Guntur',
                    'Kakinada',
                    'Krishna',
                    'Kurnool',
                    'Markapuram',
                    'NTR',
                    'Nandyal',
                    'Nellore',
                    'Palnadu',
                    'Parvathipuram Manyam',
                    'Polavaram',
                    'Prakasam',
                    'Sri Sathya Sai',
                    'Srikakulam',
                    'Tirupati',
                    'Visakhapatnam',
                    'Vizianagaram',
                    'West Godavari',
                    'YSR Kadapa',
                ],
            ],
            'Arunachal Pradesh' => [
                'code' => 'AR',
                'districts' => [
                    'Anjaw',
                    'Bichom',
                    'Changlang',
                    'East Kameng',
                    'East Siang',
                    'Kamle',
                    'Keyi Panyor',
                    'Kra Daadi',
                    'Kurung Kumey',
                    'Lepa Rada',
                    'Lohit',
                    'Longding',
                    'Lower Dibang Valley',
                    'Lower Siang',
                    'Lower Subansiri',
                    'Namsai',
                    'Pakke-Kessang',
                    'Papum Pare',
                    'Shi Yomi',
                    'Siang',
                    'Tawang',
                    'Tirap',
                    'Upper Dibang Valley',
                    'Upper Siang',
                    'Upper Subansiri',
                    'West Kameng',
                    'West Siang',
                ],
            ],
            'Assam' => [
                'code' => 'AS',
                'districts' => [
                    'Bajali',
                    'Baksa',
                    'Barpeta',
                    'Biswanath',
                    'Bongaigaon',
                    'Cachar',
                    'Charaideo',
                    'Chirang',
                    'Darrang',
                    'Dhemaji',
                    'Dhubri',
                    'Dibrugarh',
                    'Dima Hasao',
                    'Goalpara',
                    'Golaghat',
                    'Hailakandi',
                    'Hojai',
                    'Jorhat',
                    'Kamrup',
                    'Kamrup Metropolitan',
                    'Karbi Anglong',
                    'Karimganj',
                    'Kokrajhar',
                    'Lakhimpur',
                    'Majuli',
                    'Morigaon',
                    'Nagaon',
                    'Nalbari',
                    'Sivasagar',
                    'Sonitpur',
                    'South Salmara-Mankachar',
                    'Tamulpur',
                    'Tinsukia',
                    'Udalguri',
                    'West Karbi Anglong',
                ],
            ],
            'Bihar' => [
                'code' => 'BR',
                'districts' => [
                    'Araria',
                    'Arwal',
                    'Aurangabad',
                    'Banka',
                    'Begusarai',
                    'Bhagalpur',
                    'Bhojpur',
                    'Buxar',
                    'Darbhanga',
                    'East Champaran',
                    'Gaya',
                    'Gopalganj',
                    'Jamui',
                    'Jehanabad',
                    'Kaimur',
                    'Katihar',
                    'Khagaria',
                    'Kishanganj',
                    'Lakhisarai',
                    'Madhepura',
                    'Madhubani',
                    'Munger',
                    'Muzaffarpur',
                    'Nalanda',
                    'Nawada',
                    'Patna',
                    'Purnia',
                    'Rohtas',
                    'Saharsa',
                    'Samastipur',
                    'Saran',
                    'Sheikhpura',
                    'Sheohar',
                    'Sitamarhi',
                    'Siwan',
                    'Supaul',
                    'Vaishali',
                    'West Champaran',
                ],
            ],
            'Chhattisgarh' => [
                'code' => 'CG',
                'districts' => [
                    'Balod',
                    'Baloda Bazar',
                    'Balrampur-Ramanujganj',
                    'Bastar',
                    'Bemetara',
                    'Bijapur',
                    'Bilaspur',
                    'Dantewada',
                    'Dhamtari',
                    'Durg',
                    'Gariaband',
                    'Gaurela-Pendra-Marwahi',
                    'Janjgir-Champa',
                    'Jashpur',
                    'Kabirdham',
                    'Kanker',
                    'Khairagarh-Chhuikhadan-Gandai',
                    'Kondagaon',
                    'Korba',
                    'Korea',
                    'Mahasamund',
                    'Manendragarh-Chirmiri-Bharatpur',
                    'Mohla-Manpur-Ambagarh Chowki',
                    'Mungeli',
                    'Narayanpur',
                    'Raigarh',
                    'Raipur',
                    'Rajnandgaon',
                    'Sakti',
                    'Sarangarh-Bilaigarh',
                    'Sukma',
                    'Surajpur',
                    'Surguja',
                ],
            ],
            'Goa' => [
                'code' => 'GA',
                'districts' => [
                    'Kushavati',
                    'North Goa',
                    'South Goa',
                ],
            ],
            'Gujarat' => [
                'code' => 'GJ',
                'districts' => [
                    'Ahmedabad',
                    'Amreli',
                    'Anand',
                    'Aravalli',
                    'Banaskantha',
                    'Bharuch',
                    'Bhavnagar',
                    'Botad',
                    'Chhota Udaipur',
                    'Dahod',
                    'Dang',
                    'Devbhumi Dwarka',
                    'Gandhinagar',
                    'Gir Somnath',
                    'Jamnagar',
                    'Junagadh',
                    'Kheda',
                    'Kutch',
                    'Mahisagar',
                    'Mehsana',
                    'Morbi',
                    'Narmada',
                    'Navsari',
                    'Panchmahal',
                    'Patan',
                    'Porbandar',
                    'Rajkot',
                    'Sabarkantha',
                    'Surat',
                    'Surendranagar',
                    'Tapi',
                    'Vadodara',
                    'Valsad',
                    'Vav-Tharad',
                ],
            ],
            'Haryana' => [
                'code' => 'HR',
                'districts' => [
                    'Ambala',
                    'Bhiwani',
                    'Charkhi Dadri',
                    'Faridabad',
                    'Fatehabad',
                    'Gurugram',
                    'Hansi',
                    'Hisar',
                    'Jhajjar',
                    'Jind',
                    'Kaithal',
                    'Karnal',
                    'Kurukshetra',
                    'Mahendragarh',
                    'Nuh',
                    'Palwal',
                    'Panchkula',
                    'Panipat',
                    'Rewari',
                    'Rohtak',
                    'Sirsa',
                    'Sonipat',
                    'Yamunanagar',
                ],
            ],
            'Himachal Pradesh' => [
                'code' => 'HP',
                'districts' => [
                    'Bilaspur',
                    'Chamba',
                    'Hamirpur',
                    'Kangra',
                    'Kinnaur',
                    'Kullu',
                    'Lahaul and Spiti',
                    'Mandi',
                    'Shimla',
                    'Sirmaur',
                    'Solan',
                    'Una',
                ],
            ],
            'Jharkhand' => [
                'code' => 'JH',
                'districts' => [
                    'Bokaro',
                    'Chatra',
                    'Deoghar',
                    'Dhanbad',
                    'Dumka',
                    'East Singhbhum',
                    'Garhwa',
                    'Giridih',
                    'Godda',
                    'Gumla',
                    'Hazaribag',
                    'Jamtara',
                    'Khunti',
                    'Koderma',
                    'Latehar',
                    'Lohardaga',
                    'Pakur',
                    'Palamu',
                    'Ramgarh',
                    'Ranchi',
                    'Sahibganj',
                    'Seraikela-Kharsawan',
                    'Simdega',
                    'West Singhbhum',
                ],
            ],
            'Karnataka' => [
                'code' => 'KA',
                'districts' => [
                    'Bagalkot',
                    'Ballari',
                    'Bangalore Rural',
                    'Bangalore Urban',
                    'Belagavi',
                    'Bidar',
                    'Bijapur',
                    'Chamarajanagar',
                    'Chikkaballapur',
                    'Chikmagalur',
                    'Chitradurga',
                    'Dakshina Kannada',
                    'Davanagere',
                    'Dharwad',
                    'Gadaga',
                    'Hassan',
                    'Haveri',
                    'Kalaburagi',
                    'Kodagu',
                    'Kolar',
                    'Koppal',
                    'Mandya',
                    'Mysore',
                    'Raichur',
                    'Ramanagara',
                    'Shimoga',
                    'Tumakuru',
                    'Udupi',
                    'Uttara Kannada',
                    'Vijayanagara',
                    'Yadgir',
                ],
            ],
            'Kerala' => [
                'code' => 'KL',
                'districts' => [
                    'Alappuzha',
                    'Ernakulam',
                    'Idukki',
                    'Kannur',
                    'Kasaragod',
                    'Kollam',
                    'Kottayam',
                    'Kozhikode',
                    'Malappuram',
                    'Palakkad',
                    'Pathanamthitta',
                    'Thiruvananthapuram',
                    'Thrissur',
                    'Wayanad',
                ],
            ],
            'Madhya Pradesh' => [
                'code' => 'MP',
                'districts' => [
                    'Agar Malwa',
                    'Alirajpur',
                    'Anuppur',
                    'Ashoknagar',
                    'Balaghat',
                    'Barwani',
                    'Betul',
                    'Bhind',
                    'Bhopal',
                    'Burhanpur',
                    'Chhatarpur',
                    'Chhindwara',
                    'Damoh',
                    'Datia',
                    'Dewas',
                    'Dhar',
                    'Dindori',
                    'Guna',
                    'Gwalior',
                    'Harda',
                    'Hoshangabad',
                    'Indore',
                    'Jabalpur',
                    'Jhabua',
                    'Katni',
                    'Khandwa',
                    'Khargone',
                    'Maihar',
                    'Mandla',
                    'Mandsaur',
                    'Mauganj',
                    'Morena',
                    'Narsinghpur',
                    'Neemuch',
                    'Niwari',
                    'Pandhurna',
                    'Panna',
                    'Raisen',
                    'Rajgarh',
                    'Ratlam',
                    'Rewa',
                    'Sagar',
                    'Satna',
                    'Sehore',
                    'Seoni',
                    'Shahdol',
                    'Shajapur',
                    'Sheopur',
                    'Shivpuri',
                    'Sidhi',
                    'Singrauli',
                    'Tikamgarh',
                    'Ujjain',
                    'Umaria',
                    'Vidisha',
                ],
            ],
            'Maharashtra' => [
                'code' => 'MH',
                'districts' => [
                    'Ahmednagar',
                    'Akola',
                    'Amravati',
                    'Aurangabad',
                    'Beed',
                    'Bhandara',
                    'Buldhana',
                    'Chandrapur',
                    'Dhule',
                    'Gadchiroli',
                    'Gondia',
                    'Hingoli',
                    'Jalgaon',
                    'Jalna',
                    'Kolhapur',
                    'Latur',
                    'Mumbai City',
                    'Mumbai Suburban',
                    'Nagpur',
                    'Nanded',
                    'Nandurbar',
                    'Nashik',
                    'Osmanabad',
                    'Palghar',
                    'Parbhani',
                    'Pune',
                    'Raigad',
                    'Ratnagiri',
                    'Sangli',
                    'Satara',
                    'Sindhudurg',
                    'Solapur',
                    'Thane',
                    'Wardha',
                    'Washim',
                    'Yavatmal',
                ],
            ],
            'Manipur' => [
                'code' => 'MN',
                'districts' => [
                    'Bishnupur',
                    'Chandel',
                    'Churachandpur',
                    'Imphal East',
                    'Imphal West',
                    'Jiribam',
                    'Kakching',
                    'Kamjong',
                    'Kangpokpi',
                    'Noney',
                    'Pherzawl',
                    'Senapati',
                    'Tamenglong',
                    'Tengnoupal',
                    'Thoubal',
                    'Ukhrul',
                ],
            ],
            'Meghalaya' => [
                'code' => 'ML',
                'districts' => [
                    'East Garo Hills',
                    'East Jaintia Hills',
                    'East Khasi Hills',
                    'Eastern West Khasi Hills',
                    'North Garo Hills',
                    'Ri Bhoi',
                    'South Garo Hills',
                    'South West Garo Hills',
                    'South West Khasi Hills',
                    'West Garo Hills',
                    'West Jaintia Hills',
                    'West Khasi Hills',
                ],
            ],
            'Mizoram' => [
                'code' => 'MZ',
                'districts' => [
                    'Aizawl',
                    'Champhai',
                    'Hnahthial',
                    'Khawzawl',
                    'Kolasib',
                    'Lawngtlai',
                    'Lunglei',
                    'Mamit',
                    'Saiha',
                    'Saitual',
                    'Serchhip',
                ],
            ],
            'Nagaland' => [
                'code' => 'NL',
                'districts' => [
                    'Chümoukedima',
                    'Dimapur',
                    'Kiphire',
                    'Kohima',
                    'Longleng',
                    'Mokokchung',
                    'Mon',
                    'Niuland',
                    'Noklak',
                    'Peren',
                    'Phek',
                    'Shamator',
                    'Tseminyü',
                    'Tuensang',
                    'Wokha',
                    'Zunheboto',
                ],
            ],
            'Odisha' => [
                'code' => 'OD',
                'districts' => [
                    'Angul',
                    'Balangir',
                    'Balasore',
                    'Bargarh',
                    'Bhadrak',
                    'Boudh',
                    'Cuttack',
                    'Debagarh',
                    'Dhenkanal',
                    'Gajapati',
                    'Ganjam',
                    'Jagatsinghpur',
                    'Jajpur',
                    'Jharsuguda',
                    'Kalahandi',
                    'Kandhamal',
                    'Kendrapara',
                    'Kendujhar',
                    'Khordha',
                    'Koraput',
                    'Malkangiri',
                    'Mayurbhanj',
                    'Nabarangpur',
                    'Nayagarh',
                    'Nuapada',
                    'Puri',
                    'Rayagada',
                    'Sambalpur',
                    'Subarnapur',
                    'Sundargarh',
                ],
            ],
            'Punjab' => [
                'code' => 'PB',
                'districts' => [
                    'Amritsar',
                    'Barnala',
                    'Bathinda',
                    'Faridkot',
                    'Fatehgarh Sahib',
                    'Fazilka',
                    'Firozpur',
                    'Gurdaspur',
                    'Hoshiarpur',
                    'Jalandhar',
                    'Kapurthala',
                    'Ludhiana',
                    'Malerkotla',
                    'Mansa',
                    'Moga',
                    'Pathankot',
                    'Patiala',
                    'Rupnagar',
                    'Sahibzada Ajit Singh Nagar',
                    'Sangrur',
                    'Shahid Bhagat Singh Nagar',
                    'Sri Muktsar Sahib',
                    'Tarn Taran',
                ],
            ],
            'Rajasthan' => [
                'code' => 'RJ',
                'districts' => [
                    'Ajmer',
                    'Alwar',
                    'Balotra',
                    'Banswara',
                    'Baran',
                    'Barmer',
                    'Beawar',
                    'Bharatpur',
                    'Bhilwara',
                    'Bikaner',
                    'Bundi',
                    'Chittorgarh',
                    'Churu',
                    'Dausa',
                    'Deeg',
                    'Dholpur',
                    'Didwana Kuchaman',
                    'Dungarpur',
                    'Hanumangarh',
                    'Jaipur',
                    'Jaisalmer',
                    'Jalore',
                    'Jhalawar',
                    'Jhunjhunu',
                    'Jodhpur',
                    'Karauli',
                    'Khairthal-Tijara',
                    'Kota',
                    'Kotputli-Behror',
                    'Nagaur',
                    'Pali',
                    'Phalodi',
                    'Pratapgarh',
                    'Rajsamand',
                    'Salumbar',
                    'Sawai Madhopur',
                    'Sikar',
                    'Sirohi',
                    'Sri Ganganagar',
                    'Tonk',
                    'Udaipur',
                ],
            ],
            'Sikkim' => [
                'code' => 'SK',
                'districts' => [
                    'Gangtok',
                    'Gyalshing',
                    'Mangan',
                    'Namchi',
                    'Pakyong',
                    'Soreng',
                ],
            ],
            'Tamil Nadu' => [
                'code' => 'TN',
                'districts' => [
                    'Ariyalur',
                    'Chengalpattu',
                    'Chennai',
                    'Coimbatore',
                    'Cuddalore',
                    'Dharmapuri',
                    'Dindigul',
                    'Erode',
                    'Kallakurichi',
                    'Kanchipuram',
                    'Kanyakumari',
                    'Karur',
                    'Krishnagiri',
                    'Madurai',
                    'Mayiladuthurai',
                    'Nagapattinam',
                    'Namakkal',
                    'Nilgiris',
                    'Perambalur',
                    'Pudukkottai',
                    'Ramanathapuram',
                    'Ranipet',
                    'Salem',
                    'Sivaganga',
                    'Tenkasi',
                    'Thanjavur',
                    'Theni',
                    'Thoothukudi',
                    'Tiruchirappalli',
                    'Tirunelveli',
                    'Tirupattur',
                    'Tiruppur',
                    'Tiruvallur',
                    'Tiruvannamalai',
                    'Tiruvarur',
                    'Vellore',
                    'Viluppuram',
                    'Virudhunagar',
                ],
            ],
            'Telangana' => [
                'code' => 'TG',
                'districts' => [
                    'Adilabad',
                    'Bhadradri Kothagudem',
                    'Hanamkonda',
                    'Hyderabad',
                    'Jagtial',
                    'Jangaon',
                    'Jayashankar Bhupalpally',
                    'Jogulamba Gadwal',
                    'Kamareddy',
                    'Karimnagar',
                    'Khammam',
                    'Kumuram Bheem Asifabad',
                    'Mahabubabad',
                    'Mahbubnagar',
                    'Mancherial',
                    'Medak',
                    'Medchal–Malkajgiri',
                    'Mulugu',
                    'Nagarkurnool',
                    'Nalgonda',
                    'Narayanpet',
                    'Nirmal',
                    'Nizamabad',
                    'Peddapalli',
                    'Rajanna Sircilla',
                    'Ranga Reddy',
                    'Sangareddy',
                    'Siddipet',
                    'Suryapet',
                    'Vikarabad',
                    'Wanaparthy',
                    'Warangal',
                    'Yadadri Bhuvanagiri',
                ],
            ],
            'Tripura' => [
                'code' => 'TR',
                'districts' => [
                    'Dhalai',
                    'Gomati',
                    'Khowai',
                    'North Tripura',
                    'Sepahijala',
                    'South Tripura',
                    'Unakoti',
                    'West Tripura',
                ],
            ],
            'Uttar Pradesh' => [
                'code' => 'UP',
                'districts' => [
                    'Agra',
                    'Aligarh',
                    'Ambedkar Nagar',
                    'Amethi',
                    'Amroha',
                    'Auraiya',
                    'Ayodhya',
                    'Azamgarh',
                    'Bagpat',
                    'Bahraich',
                    'Ballia',
                    'Balrampur',
                    'Banda',
                    'Barabanki',
                    'Bareilly',
                    'Basti',
                    'Bhadohi',
                    'Bijnor',
                    'Budaun',
                    'Bulandshahr',
                    'Chandauli',
                    'Chitrakoot',
                    'Deoria',
                    'Etah',
                    'Etawah',
                    'Farrukhabad',
                    'Fatehpur',
                    'Firozabad',
                    'Gautam Buddha Nagar',
                    'Ghaziabad',
                    'Ghazipur',
                    'Gonda',
                    'Gorakhpur',
                    'Hamirpur',
                    'Hapur',
                    'Hardoi',
                    'Hathras',
                    'Jalaun',
                    'Jaunpur',
                    'Jhansi',
                    'Kannauj',
                    'Kanpur Dehat',
                    'Kanpur Nagar',
                    'Kasganj',
                    'Kaushambi',
                    'Kushinagar',
                    'Lakhimpur Kheri',
                    'Lalitpur',
                    'Lucknow',
                    'Maharajganj',
                    'Mahoba',
                    'Mainpuri',
                    'Mathura',
                    'Mau',
                    'Meerut',
                    'Mirzapur',
                    'Moradabad',
                    'Muzaffarnagar',
                    'Pilibhit',
                    'Pratapgarh',
                    'Prayagraj',
                    'Raebareli',
                    'Rampur',
                    'Saharanpur',
                    'Sambhal',
                    'Sant Kabir Nagar',
                    'Shahjahanpur',
                    'Shamli',
                    'Shravasti',
                    'Siddharthnagar',
                    'Sitapur',
                    'Sonbhadra',
                    'Sultanpur',
                    'Unnao',
                    'Varanasi',
                ],
            ],
            'Uttarakhand' => [
                'code' => 'UK',
                'districts' => [
                    'Almora',
                    'Bageshwar',
                    'Chamoli',
                    'Champawat',
                    'Dehradun',
                    'Haridwar',
                    'Nainital',
                    'Pauri Garhwal',
                    'Pithoragarh',
                    'Rudraprayag',
                    'Tehri Garhwal',
                    'Udham Singh Nagar',
                    'Uttarkashi',
                ],
            ],
            'West Bengal' => [
                'code' => 'WB',
                'districts' => [
                    'Alipurduar',
                    'Bankura',
                    'Birbhum',
                    'Cooch Behar',
                    'Dakshin Dinajpur',
                    'Darjeeling',
                    'Hooghly',
                    'Howrah',
                    'Jalpaiguri',
                    'Jhargram',
                    'Kalimpong',
                    'Kolkata',
                    'Maldah',
                    'Murshidabad',
                    'Nadia',
                    'North 24 Parganas',
                    'Paschim Bardhaman',
                    'Paschim Medinipur',
                    'Purba Bardhaman',
                    'Purba Medinipur',
                    'Purulia',
                    'South 24 Parganas',
                    'Uttar Dinajpur',
                ],
            ],
            'Andaman and Nicobar Islands' => [
                'code' => 'AN',
                'districts' => [
                    'Nicobar',
                    'North and Middle Andaman',
                    'South Andaman',
                ],
            ],
            'Chandigarh' => [
                'code' => 'CH',
                'districts' => [
                    'Chandigarh',
                ],
            ],
            'Dadra and Nagar Haveli and Daman and Diu' => [
                'code' => 'DH',
                'districts' => [
                    'Dadra and Nagar Haveli',
                    'Daman',
                    'Diu',
                ],
            ],
            'Jammu and Kashmir' => [
                'code' => 'JK',
                'districts' => [
                    'Anantnag',
                    'Bandipore',
                    'Baramulla',
                    'Budgam',
                    'Doda',
                    'Ganderbal',
                    'Jammu',
                    'Kathua',
                    'Kishtwar',
                    'Kulgam',
                    'Kupwara',
                    'Poonch',
                    'Pulwama',
                    'Rajouri',
                    'Ramban',
                    'Reasi',
                    'Samba',
                    'Shopian',
                    'Srinagar',
                    'Udhampur',
                ],
            ],
            'Ladakh' => [
                'code' => 'LA',
                'districts' => [
                    'Changthang',
                    'Drass',
                    'Kargil',
                    'Leh',
                    'Nubra',
                    'Sham',
                    'Zanskar',
                ],
            ],
            'Lakshadweep' => [
                'code' => 'LD',
                'districts' => [
                    'Lakshadweep',
                ],
            ],
            'Delhi' => [
                'code' => 'DL',
                'districts' => [
                    'Central Delhi',
                    'East Delhi',
                    'New Delhi',
                    'North Delhi',
                    'North East Delhi',
                    'North West Delhi',
                    'Shahdara',
                    'South Delhi',
                    'South East Delhi',
                    'South West Delhi',
                    'West Delhi',
                ],
            ],
            'Puducherry' => [
                'code' => 'PY',
                'districts' => [
                    'Karaikal',
                    'Mahé',
                    'Puducherry',
                    'Yanam',
                ],
            ],
        ];
    }
}
